name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.22.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          make install

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make clean

          GOOSARCHES=(
            darwin/amd64
            darwin/arm64
            freebsd/amd64
            freebsd/386
            linux/arm
            linux/arm64
            linux/amd64
            linux/386
            windows/amd64
            windows/386
          )

          for GOOSARCH in "${GOOSARCHES[@]}"; do
            GOOS=${GOOSARCH%/*}
            ARCH=${GOOSARCH#*/}

            echo "\n\nBuilding binary for ${GOOS}/${ARCH}\n"

            GIT_RELEASE=${{ github.event.release.tag_name }} GOOS=${GOOS} GOARCH=${ARCH} make static-named
          done

          gh release upload ${{ github.event.release.tag_name }} build/*

      - name: Release notification
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: "product-releases"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Prolific CLI versioned release* - ${{ job.status }}\n*Git reference* - ${{ github.event.release.tag_name }}\n*Deployed by* ${{ github.actor }}\n\n<${{ github.event.release.html_url || github.event.head_commit.url }}|${{ github.event.release.tag_name }} Release>"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
